spring:
  application:
    name: farasiapp-matching-api
  profiles:
  - prod
  data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: '${MONGO_PORT}'
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
      authentication-database: '${MONGO_AUTH_DB}'  
      
api:
  api-secrete: '${API_SECRETE}'
  api-version: '${API_VERSION}'
  api-username: '${API_USERNAME}'
  api-password: '${API_PASSWORD}'         
      
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

server:
  max-http-header-size: 10000000
  
logging:
  config: classpath:logback.xml   