spring:
  application:
    name: farasiapp-matching-api
  profiles:
  - dev
  data:
    mongodb:
      host: localhost
      database: dev
      port: 27017
      username: basil
      password: password
      authentication-database: admin    
api:
  api-secrete: password
  api-version: 1.0.0 
  api-username: admin
  api-password: admin  
      
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

server:
  max-http-header-size: 10000000
   