apiVersion: apps/v1
kind: Deployment
metadata:
  name: farasiapp-matching-api
  labels:
    app: farasiapp-matching-api
    tier: microservice
spec:
  selector:
      matchLabels:
        app: farasiapp-matching-api
  replicas: 1
  template:
    metadata:
      labels:
        app: farasiapp-matching-api
    spec:
      containers:
        - name: farasiapp-matching-api
          image: basiljereh/farasiapp-matching-api:latest
          ports:
          - containerPort: 8080
          env:        
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrete-farasiapp-matching-api
                  key: mongo.database.username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrete-farasiapp-matching-api
                  key: mongo.database.password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap  
                  key: mongo.database.name
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap
                  key: mongo.database.host  
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap
                  key: mongo.database.port                    
            - name: MONGO_AUTH_DB
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap
                  key: mongo.authentication.database                      
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap
                  key: api.version
            - name: API_SECRETE
              valueFrom:
                secretKeyRef:
                  name: secrete-farasiapp-matching-api
                  key: api.secrete
            - name: API_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap
                  key:  api.username
            - name: API_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: farasiapp-matching-api-configmap
                  key:  api.password  
            - name: TZ
              value: Africa/Nairobi                                  
          imagePullPolicy: Always 
---
apiVersion: v1
kind: Service
metadata:
  name: farasiapp-matching-api-service
spec:
  selector:
    app: farasiapp-matching-api
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30003
  type: NodePort                                  
