server:
  max-http-header-size: 10000000

spring:
  application:
    name: farasiapp-matching-api
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/farasiapp
          
api:
  api-secrete: password
  api-version: 1.0.0 
  api-username: admin
  api-password: admin    